# Generated by Django 4.2.30 on 2026-06-09 14:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttemplate',
            options={'ordering': ['display_order', 'label']},
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='night_bonus_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.CreateModel(
            name='UserSiteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('site_user', 'Usuario por sede')], default='site_user', max_length=20)),
                ('sites', models.ManyToManyField(blank=True, related_name='user_access_profiles', to='core.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso por usuario',
                'verbose_name_plural': 'Accesos por usuario',
                'ordering': ['user__username'],
            },
        ),
    ]
