# Generated by Django 4.2.30 on 2026-06-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shifttemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='areas',
        ),
        migrations.AlterModelTable(
            name='jobrole',
            table='parametros_cargos',
        ),
        migrations.AlterModelTable(
            name='shifttemplate',
            table='catalogo_turnos',
        ),
        migrations.AlterModelTable(
            name='site',
            table='sedes',
        ),
        migrations.AlterModelTable(
            name='systemconfiguration',
            table='configuracion_sistema',
        ),
        migrations.AlterModelTable(
            name='usersiteaccess',
            table='accesos_usuario_sede',
        ),
    ]
