# Generated by Django 4.2.30 on 2026-06-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_department_table_alter_jobrole_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersiteaccess',
            name='sites',
            field=models.ManyToManyField(blank=True, db_table='accesos_usuario_sede_sedes', related_name='user_access_profiles', to='core.site'),
        ),
    ]
