# Generated by Django 4.2.30 on 2026-06-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usersiteaccess_sites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='jobrole',
            options={'ordering': ['name'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='shifttemplate',
            options={'ordering': ['display_order', 'label'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['code'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
    ]
