# Generated by Codex on 2026-06-18

from datetime import datetime, time
from decimal import Decimal

from django.db import migrations


def normalize_shift_end_time(apps, schema_editor):
    ShiftTemplate = apps.get_model("core", "ShiftTemplate")
    anchor_date = datetime.today().date()

    for shift in ShiftTemplate.objects.filter(end_time=time(21, 30)):
        if not shift.start_time or shift.end_time <= shift.start_time:
            continue
        shift.end_time = time(21, 0)
        start_value = datetime.combine(anchor_date, shift.start_time)
        end_value = datetime.combine(anchor_date, shift.end_time)
        shift.duration_hours = Decimal(str((end_value - start_value).total_seconds() / 3600)).quantize(Decimal("0.01"))
        shift.save(update_fields=["end_time", "duration_hours"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_department_options_alter_jobrole_options_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_shift_end_time, migrations.RunPython.noop),
    ]
