# Generated by Django 4.2.30 on 2026-06-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_normalize_shift_end_time_to_2100'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF to_regclass('public.cache_personal_operativo') IS NULL
                    AND to_regclass('public.cache_personal_operativo_id_seq') IS NOT NULL THEN
                        DROP SEQUENCE public.cache_personal_operativo_id_seq CASCADE;
                    END IF;
                END
                $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='OperationalStaffCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_code', models.CharField(max_length=10)),
                ('employee_identifier', models.CharField(max_length=30)),
                ('employee_name', models.CharField(max_length=180)),
                ('department_code', models.CharField(blank=True, max_length=20)),
                ('department_name', models.CharField(blank=True, max_length=120)),
                ('role_code', models.CharField(blank=True, max_length=20)),
                ('role_name', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cache de personal operativo',
                'verbose_name_plural': 'Cache de personal operativo',
                'db_table': 'cache_personal_operativo',
                'ordering': ['site_code', 'role_name', 'employee_name', 'employee_identifier'],
                'indexes': [models.Index(fields=['site_code', 'is_active'], name='idx_cache_oper_sede_activa'), models.Index(fields=['employee_identifier'], name='idx_cache_oper_cedula'), models.Index(fields=['site_code', 'role_name', 'employee_name'], name='idx_cache_oper_sede_cargo_nom')],
            },
        ),
        migrations.AddConstraint(
            model_name='operationalstaffcache',
            constraint=models.UniqueConstraint(fields=('site_code', 'employee_identifier'), name='uq_cache_personal_sede_cedula'),
        ),
    ]
