# Generated by Django 4.2.30 on 2026-07-09 13:38

import datetime
from django.db import migrations, models


def seed_initial_holidays(apps, schema_editor):
    Holiday = apps.get_model("core", "Holiday")
    Holiday.objects.update_or_create(
        holiday_date=datetime.date(2026, 7, 13),
        defaults={
            "name": "Festivo configurado manualmente",
            "is_active": True,
            "notes": "Precargado para la operacion semanal del portal.",
        },
    )


def remove_initial_holidays(apps, schema_editor):
    Holiday = apps.get_model("core", "Holiday")
    Holiday.objects.filter(holiday_date=datetime.date(2026, 7, 13)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_site_admin_only_and_personal_vario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holiday_date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=220)),
            ],
            options={
                'verbose_name': 'Festivo',
                'verbose_name_plural': 'Festivos',
                'db_table': 'festivos_configurados',
                'ordering': ['holiday_date'],
            },
        ),
        migrations.RunPython(seed_initial_holidays, remove_initial_holidays),
    ]
