# Generated by Django 4.2.30 on 2026-07-15 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='base_work_days',
            field=models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_base_work_days',
            field=models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
