# Generated by Django 4.2.30 on 2026-09-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_contractacion_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersiteaccess',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('auditor', 'Consulta / auditoria'), ('site_user', 'Usuario por sede')], default='site_user', max_length=20),
        ),
    ]
