# Generated by Django 4.2.30 on 2026-06-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyCostCenter',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=120)),
            ],
            options={
                'db_table': 'centro_costo',
                'ordering': ['description'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyEmployee',
            fields=[
                ('employee_id', models.CharField(db_column='empleado', max_length=30, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, db_column='nombre_completo', max_length=180)),
                ('site_code', models.CharField(blank=True, db_column='id_co', max_length=10)),
                ('cost_center_code', models.CharField(blank=True, db_column='id_ccosto', max_length=20)),
                ('role_code', models.CharField(blank=True, db_column='id_cargo', max_length=20)),
                ('role_name', models.CharField(blank=True, db_column='nombre_cargo', max_length=180)),
                ('contract_status', models.CharField(blank=True, db_column='estado_contrato', max_length=5)),
                ('withdrawal_date', models.CharField(blank=True, db_column='fecha_retiro', max_length=20)),
            ],
            options={
                'db_table': 'hojas_de_vida',
                'ordering': ['full_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyOperationalSite',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=120)),
                ('group_code', models.CharField(blank=True, db_column='grupo_co', max_length=10)),
            ],
            options={
                'db_table': 'centro_operacion',
                'ordering': ['code'],
                'managed': False,
            },
        ),
    ]
