# Generated by Django 6.0.6 on 2026-06-09 14:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField(blank=True, null=True)),
                ('first_day_index', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], default=6)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En revision'), ('published', 'Publicado')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_schedules', to='core.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date', 'site__code'],
                'unique_together': {('site', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_identifier', models.CharField(max_length=30)),
                ('employee_name', models.CharField(max_length=180)),
                ('department_code', models.CharField(blank=True, max_length=20)),
                ('department_name', models.CharField(blank=True, max_length=120)),
                ('job_role_code', models.CharField(blank=True, max_length=30)),
                ('job_role_name', models.CharField(blank=True, max_length=140)),
                ('weekly_target_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('daily_max_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('day_0_shift_1', models.CharField(blank=True, max_length=40)),
                ('day_0_shift_2', models.CharField(blank=True, max_length=40)),
                ('day_0_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('day_1_shift_1', models.CharField(blank=True, max_length=40)),
                ('day_1_shift_2', models.CharField(blank=True, max_length=40)),
                ('day_1_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('day_2_shift_1', models.CharField(blank=True, max_length=40)),
                ('day_2_shift_2', models.CharField(blank=True, max_length=40)),
                ('day_2_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('day_3_shift_1', models.CharField(blank=True, max_length=40)),
                ('day_3_shift_2', models.CharField(blank=True, max_length=40)),
                ('day_3_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('day_4_shift_1', models.CharField(blank=True, max_length=40)),
                ('day_4_shift_2', models.CharField(blank=True, max_length=40)),
                ('day_4_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('day_5_shift_1', models.CharField(blank=True, max_length=40)),
                ('day_5_shift_2', models.CharField(blank=True, max_length=40)),
                ('day_5_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('day_6_shift_1', models.CharField(blank=True, max_length=40)),
                ('day_6_shift_2', models.CharField(blank=True, max_length=40)),
                ('day_6_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('pending_dates_note', models.CharField(blank=True, max_length=140)),
                ('pending_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('pending_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('pending_hours_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('validation_summary', models.TextField(blank=True)),
                ('warnings_count', models.PositiveSmallIntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='schedules.weeklyschedule')),
            ],
            options={
                'ordering': ['department_name', 'employee_name'],
                'unique_together': {('schedule', 'employee_identifier')},
            },
        ),
    ]
