# Generated by Django 4.2.30 on 2026-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleline',
            name='pending_dates_note',
            field=models.TextField(blank=True),
        ),
    ]
