# Generated by Django 4.2.30 on 2026-06-09 16:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_scheduleline_pending_dates_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='night_bonus_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
