# Generated by Django 4.2.30 on 2026-06-09 21:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_scheduleline_night_bonus_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='day_0_compensation_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_0_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas')], max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_1_compensation_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_1_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas')], max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_2_compensation_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_2_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas')], max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_3_compensation_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_3_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas')], max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_4_compensation_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_4_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas')], max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_5_compensation_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_5_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas')], max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_6_compensation_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='day_6_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas')], max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='payment_days_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='payment_hours_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
