# Generated by Django 4.2.30 on 2026-06-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_scheduleline_day_0_compensation_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='employee_document_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
