# Generated by Django 4.2.30 on 2026-06-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_scheduleline_employee_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleline',
            options={'ordering': ['job_role_name', 'employee_name', 'department_name']},
        ),
    ]
