# Generated by Django 4.2.30 on 2026-06-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_alter_scheduleline_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scheduleline',
            table='horarios_detalle',
        ),
        migrations.AlterModelTable(
            name='weeklyschedule',
            table='horarios_semanales',
        ),
    ]
