# Generated by Django 4.2.30 on 2026-06-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_alter_scheduleline_table_alter_weeklyschedule_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleline',
            options={'ordering': ['job_role_name', 'employee_name', 'department_name'], 'verbose_name': 'Detalle de horario', 'verbose_name_plural': 'Detalle de horarios'},
        ),
        migrations.AlterModelOptions(
            name='weeklyschedule',
            options={'ordering': ['-week_start_date', 'site__code'], 'verbose_name': 'Horario semanal', 'verbose_name_plural': 'Horarios semanales'},
        ),
    ]
