# Generated by Django 4.2.30 on 2026-06-18 15:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def rebuild_existing_schedule_balances(apps, schema_editor):
    from schedules.models import ScheduleLine
    from schedules.services import save_schedule_line_with_balances

    queryset = ScheduleLine.objects.select_related("schedule").order_by("schedule__week_start_date", "pk")
    for line in queryset.iterator():
        if not line.manual_day_adjustment and line.pending_days:
            line.manual_day_adjustment = line.pending_days
        if not line.manual_hour_adjustment and line.pending_hours:
            line.manual_hour_adjustment = line.pending_hours
        save_schedule_line_with_balances(line)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_department_options_alter_jobrole_options_and_more'),
        ('schedules', '0008_alter_scheduleline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='accrued_day_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='accrued_hour_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='accrued_total_hours_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='manual_day_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='manual_hour_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='money_payment_hours_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='special_days_generated',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_0_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('pay_money', 'Pago dinero')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_1_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('pay_money', 'Pago dinero')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_2_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('pay_money', 'Pago dinero')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_3_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('pay_money', 'Pago dinero')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_4_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('pay_money', 'Pago dinero')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_5_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('pay_money', 'Pago dinero')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_6_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('pay_money', 'Pago dinero')], max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduleBalanceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_identifier', models.CharField(max_length=30)),
                ('employee_name', models.CharField(max_length=180)),
                ('job_role_name', models.CharField(blank=True, max_length=140)),
                ('movement_date', models.DateField()),
                ('movement_type', models.CharField(choices=[('overtime', 'Hora extra generada'), ('special_day', 'Domingo o festivo laborado'), ('manual_day', 'Ajuste manual de dias'), ('manual_hour', 'Ajuste manual de horas'), ('pay_day', 'Pago con descanso'), ('pay_hours', 'Pago con horas'), ('pay_money', 'Pago en dinero')], max_length=30)),
                ('quantity_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('quantity_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('equivalent_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_movements', to='schedules.scheduleline')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_movements', to='schedules.weeklyschedule')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_movements', to='core.site')),
            ],
            options={
                'verbose_name': 'Movimiento de saldo',
                'verbose_name_plural': 'Movimientos de saldo',
                'db_table': 'movimientos_saldo_horario',
                'ordering': ['movement_date', 'employee_identifier', 'pk'],
            },
        ),
        migrations.RunPython(rebuild_existing_schedule_balances, migrations.RunPython.noop),
    ]
