# Generated by Django 4.2.30 on 2026-06-18 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0009_scheduleline_accrued_day_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSettlementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=180)),
                ('pdf_content', models.BinaryField()),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_settlement_documents', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_document', to='schedules.weeklyschedule')),
            ],
            options={
                'verbose_name': 'Paz y salvo semanal',
                'verbose_name_plural': 'Paz y salvo semanales',
                'db_table': 'paz_y_salvo_semanal',
                'ordering': ['-schedule__week_start_date', 'schedule__site__code'],
            },
        ),
    ]
