# Generated by Django 4.2.30 on 2026-06-22 19:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0010_schedulesettlementdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInitialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_identifier', models.CharField(max_length=30, unique=True)),
                ('employee_name', models.CharField(blank=True, max_length=180)),
                ('initial_day_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('initial_hour_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_initial_balances', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_initial_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo inicial por empleado',
                'verbose_name_plural': 'Saldos iniciales por empleado',
                'db_table': 'saldos_iniciales_personal',
                'ordering': ['employee_identifier'],
            },
        ),
    ]
