# Generated by Django 4.2.30 on 2026-06-22 22:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_employeeinitialbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOvertimeRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_identifier', models.CharField(max_length=30, unique=True)),
                ('employee_name', models.CharField(blank=True, max_length=180)),
                ('max_weekly_overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Restriccion de horas extra',
                'verbose_name_plural': 'Restricciones de horas extra',
                'db_table': 'restricciones_horas_extra_personal',
                'ordering': ['employee_identifier'],
            },
        ),
    ]
