# Generated by Django 4.2.30 on 2026-06-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_employeeovertimerestriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleline',
            name='pending_dates_note',
        ),
        migrations.RemoveField(
            model_name='scheduleline',
            name='pending_days',
        ),
        migrations.RemoveField(
            model_name='scheduleline',
            name='pending_hours',
        ),
        migrations.RemoveField(
            model_name='scheduleline',
            name='pending_hours_variance',
        ),
    ]
