# Generated by Django 4.2.30 on 2026-06-22 23:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_remove_scheduleline_pending_dates_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeovertimerestriction',
            name='max_daily_overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
