# Generated by Django 4.2.30 on 2026-06-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_employeeovertimerestriction_max_daily_overtime_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeScheduleBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_identifier', models.CharField(max_length=30, unique=True)),
                ('employee_name', models.CharField(blank=True, max_length=180)),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lista negra de horarios',
                'verbose_name_plural': 'Lista negra de horarios',
                'db_table': 'lista_negra_horarios_personal',
                'ordering': ['employee_identifier'],
            },
        ),
    ]
