# Generated by Django 4.2.30 on 2026-06-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_employeescheduleblacklist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedulebalancemovement',
            index=models.Index(fields=['employee_identifier'], name='idx_mov_saldo_cedula'),
        ),
        migrations.AddIndex(
            model_name='scheduleline',
            index=models.Index(fields=['employee_identifier'], name='idx_horarios_det_cedula'),
        ),
        migrations.AddIndex(
            model_name='weeklyschedule',
            index=models.Index(fields=['week_start_date'], name='idx_horarios_semana_inicio'),
        ),
    ]
