# Generated by Django 4.2.30 on 2026-07-09 21:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0019_weeklyschedule_admin_edit_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='advance_rest_days_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='advance_rest_pending_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='expected_weekly_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='expected_work_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='weekly_hour_difference',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='schedulebalancemovement',
            name='movement_type',
            field=models.CharField(choices=[('overtime', 'Hora extra generada'), ('hour_deficit', 'Horas faltantes'), ('special_day', 'Domingo o festivo laborado'), ('manual_day', 'Ajuste manual de dias'), ('manual_hour', 'Ajuste manual de horas'), ('pay_day', 'Pago con descanso'), ('advance_day', 'Descanso adelantado'), ('pay_hours', 'Pago con horas'), ('pay_money_day', 'Pago en dinero por dia'), ('pay_money_hours', 'Pago en dinero por horas'), ('pay_money', 'Pago en dinero (anterior)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_0_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('advance_day', 'Descanso adelantado'), ('pay_money_day', 'Pago dinero dia'), ('pay_money_hours', 'Pago dinero horas'), ('pay_money', 'Pago dinero horas (anterior)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_1_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('advance_day', 'Descanso adelantado'), ('pay_money_day', 'Pago dinero dia'), ('pay_money_hours', 'Pago dinero horas'), ('pay_money', 'Pago dinero horas (anterior)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_2_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('advance_day', 'Descanso adelantado'), ('pay_money_day', 'Pago dinero dia'), ('pay_money_hours', 'Pago dinero horas'), ('pay_money', 'Pago dinero horas (anterior)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_3_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('advance_day', 'Descanso adelantado'), ('pay_money_day', 'Pago dinero dia'), ('pay_money_hours', 'Pago dinero horas'), ('pay_money', 'Pago dinero horas (anterior)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_4_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('advance_day', 'Descanso adelantado'), ('pay_money_day', 'Pago dinero dia'), ('pay_money_hours', 'Pago dinero horas'), ('pay_money', 'Pago dinero horas (anterior)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_5_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('advance_day', 'Descanso adelantado'), ('pay_money_day', 'Pago dinero dia'), ('pay_money_hours', 'Pago dinero horas'), ('pay_money', 'Pago dinero horas (anterior)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleline',
            name='day_6_compensation_mode',
            field=models.CharField(blank=True, choices=[('', 'Sin pago'), ('pay_day', 'Pago dia'), ('pay_hours', 'Pago horas'), ('advance_day', 'Descanso adelantado'), ('pay_money_day', 'Pago dinero dia'), ('pay_money_hours', 'Pago dinero horas'), ('pay_money', 'Pago dinero horas (anterior)')], max_length=20),
        ),
    ]
