# Generated by Django 4.2.30 on 2026-07-15 00:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0020_scheduleline_advance_rest_days_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulebalancemovement',
            name='balance_after_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='schedulebalancemovement',
            name='balance_before_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='schedulebalancemovement',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='schedulebalancemovement',
            name='is_reversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulebalancemovement',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulebalancemovement',
            name='movement_origin',
            field=models.CharField(default='horario', max_length=40),
        ),
        migrations.AddField(
            model_name='schedulebalancemovement',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_schedule_balance_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulebalancemovement',
            name='reversed_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='schedules.schedulebalancemovement'),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='available_capacity_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='base_work_days',
            field=models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='validation_status',
            field=models.CharField(choices=[('VALIDA', 'Valida'), ('INCOMPLETA_CORREGIBLE', 'Incompleta corregible'), ('EXCESO_PROGRAMADO', 'Exceso programado'), ('IMPOSIBLE_POR_CAPACIDAD', 'Imposible por capacidad'), ('EXCEPCION_AUTORIZADA', 'Excepcion autorizada'), ('INCONSISTENTE', 'Inconsistente')], default='VALIDA', max_length=32),
        ),
        migrations.AlterField(
            model_name='schedulebalancemovement',
            name='movement_type',
            field=models.CharField(choices=[('overtime', 'Hora extra generada'), ('hour_deficit', 'Horas faltantes'), ('special_day', 'Domingo o festivo laborado'), ('additional_rest', 'Descanso adicional disfrutado'), ('manual_day', 'Ajuste manual de dias'), ('manual_hour', 'Ajuste manual de horas'), ('pay_day', 'Pago con descanso'), ('advance_day', 'Descanso adelantado'), ('pay_hours', 'Pago con horas'), ('pay_money_day', 'Pago en dinero por dia'), ('pay_money_hours', 'Pago en dinero por horas'), ('pay_money', 'Pago en dinero (anterior)'), ('reversal', 'Reverso')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='schedulebalancemovement',
            index=models.Index(fields=['employee_identifier', 'movement_date'], name='idx_mov_saldo_ced_fec'),
        ),
        migrations.AddIndex(
            model_name='schedulebalancemovement',
            index=models.Index(fields=['idempotency_key'], name='idx_mov_saldo_idempot'),
        ),
    ]
